### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by LinXnan** [quericy/Teaching-interactive-web-platform#2]
请问下载你的项目之后，怎么让他运行起来，地址栏怎么输入？谢谢

**Comment by quericy** [comment]
这取决于你使用的环境。。。
+ 请先确保你的本地有正确安装PHP的环境，如果没装，可以参考 [入门指南](https://laravel-china.github.io/php-the-right-way/#getting_started) 进行安装；

+ 如果你使用服务器或者免费空间，可参考 [服务器部署](https://laravel-china.github.io/php-the-right-way/#servers_and_deployment) 搭建环境；

+ 然后项目的运行，这个是基于CodeIgniter2的框架，可以参考 [官方中文文档](http://codeigniter.org.cn/userguide2/toc.html) ，着重关注其中的 [安装指导](http://codeigniter.org.cn/userguide2/installation/index.html) 一节；

**Comment by LinXnan** [comment]
我就是把你的整个项目放到了服务器的www目录下，然后地址输入http://localhost:808/Teaching-interactive-web-platform-master/index.php，结果显示500错误，请问我的地址得怎么输入
