### ISSUE TITLE
本项目的问题请教大佬

### ISSUE THREAD

**Issue by Allen151** [quericy/Teaching-interactive-web-platform#3]
您好大佬：
首先非常感谢大佬的分享，我很快速就体验上了这个系统。
我在使用过程中有两功能无法使用：
1、学生端无法上传文档。
2、学生与老师都无法在答疑中回复答案。
尝试着去解决，没有搞掂，希望大佬能指点一下。

**Comment by quericy** [comment]
这个项目是好几年前挖的坑，具体细节已经记不清了，刚才大致看了一下：

`1、学生端无法上传文档。`
这里两个字段应该没用上，大概当时预留的字段没写对应逻辑，提交字段里没有默认值，默认置空即可。
```sql
ALTER TABLE `table_work_process` CHANGE `content` `content` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '作业内容';

ALTER TABLE `table_file` CHANGE `uri` `uri` INT(11) NULL DEFAULT NULL COMMENT '附件路径uri';
```

`2、学生与老师都无法在答疑中回复答案。`
这个是因为答疑表的UA字段预留的长度太小了:
```sql
ALTER TABLE `table_answer` CHANGE `UA` `UA` VARCHAR(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '代理字符串';
```

其他问题可以通过打印的错误信息来排查:
```php
ini_set('display_errors', true);
error_reporting(E_ALL);
```

**Comment by quericy** [comment]
master分支已更新，对应部分已修正.

**Comment by Allen151** [comment]
大佬回复这么快，多谢了，已经解决，非常不错的网站，排版也非常漂亮。
对于我这种在校学生，学习经验欠缺的学生，这是十分好的案例。感谢分享。
现在我在使用的过程中还发现两个问题。
就是：

1、主页底部，已发布作业、已上交作业、专业教师、最新留言这几项中，已上交作业页面的跳是与已发布的页面是一样的吗？

2、还有就是专业教师的页面丢失了，好像。
