### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by AntRunning2019** [quericy/Teaching-interactive-web-platform#4]

**Comment by AntRunning2019** [comment]
如果可以的话给我发一下，我的邮箱是pung.jia2019@gmail.com,
在次感谢

**Comment by quericy** [comment]
我手头没有留存，不好意思。

另外作为一个四年前的项目，其使用的技术已经过时。
无论是CI2，还是JQuery+Bootstrap，已经与当前最新的技术栈脱节。

如果出于学习的目的，建议你可以参考一些较新的技术组合方案(如Laravel+Vue.js，React+Antd)，你能了解到更多新知识以及有意思的东西

**Comment by AntRunning2019** [comment]
谢谢啦，我是一个PHP新手，非常感谢你给我指点 pung Shuaige 邮箱pung.jia2019@gmail.com 签名由 网易邮箱大师 定制 在2019年03月21日 20:53，quericy 写道： 我手头没有留存，不好意思。 另外作为一个四年前的项目，其使用的技术已经过时。 无论是CI2，还是JQuery+Bootstrap，已经与当前最新的技术栈脱节。 如果出于学习的目的，建议你可以参考一些较新的技术组合方案(如Laravel+Vue.js，React+Antd)，你能了解到更多新知识以及有意思的东西 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
